spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:c:/tmp/testdb
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
  thymeleaf:
    cache: false